version: '3.8'

services:
  myapp:
    build: .
    container_name: money-transfer-app-container
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgressetup-ahmedamin372002-157b.g.aivencloud.com:10193/defaultdb
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_0We6IrpmdrKXN0zxEVS
    volumes:
      - ./target/Transfer-Service-0.0.1-SNAPSHOT.jar:/money-transfer-app.jar
    entrypoint: ["java", "-jar", "/money-transfer-app.jar"]
